version: "3.9"
services:
  speedtest-runner:
    build: .
    depends_on:
      - influx
    command: ["./wait-for-it.sh", "influx:8086", "--", "python", "speedtest.py"]
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    container_name: speedtest-runner
    restart: always
  influx:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    volumes:
      - influxdb2:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=speedtest-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    container_name: influx-database
    restart: always
  grafana:
    image: grafana/grafana:8.0.6-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    container_name: grafana-dashboard
    restart: always
volumes:
  influxdb2:
  grafana:
